production:
 host: flame.mongohq.com
 port: 27077
 database: MagicDeck
 username: logicbydesign
 password: evaunit1

development:
  host: flame.mongohq.com
  port: 27077
  database: MagicDeck
  username: logicbydesign
  password: zelda1

test:
  host: localhost
  database: tdb-test
